repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: run_tests
    language: script
    name: Run tests
    entry: ./run_test.sh
    stage: [commit]