repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
    - id: run_tests
      language: script
      name: Run tests
      entry: ./run_test.sh
    - id: run_pylint
      language: script
      name: Run pylint
      entry: ./run_pylint.sh
    # - id: coverage
    #   name: coverage
    #   stages: [commit]
    #   language: system
    #   entry: coverage report --fail-under=50 --omit __init__.py
    #   types: [python]
    #   pass_filenames: false
