[project]
name = "isecapipy"
version = "0.0.1"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 100
src = ["src"]